### ISSUE TITLE
Allow multiple users to verify the same changeset

### ISSUE THREAD

**Issue by naoliv** [willemarcel/osmcha-django#25] opened 2016-01-21 13:02 UTC
It should be allowed to multiple users verify the same changeset.

**Comment by willemarcel** [comment] 2016-01-23 02:02
I've thought about the possibility of a user recheck a changeset marked as good and change the status from good to harmful... If the changeset was first marked as harmful, we can understand that the user fixed or reverted it already (maybe it is not well explained in the interface, but I'll improve it now).

What do you think? The problem is that we have one field indicating if the changeset is harmful or not. If there is more than one verification, what would we set to this field?

**Comment by willemarcel** [comment] 2016-01-23 02:14
I added a message alerting to fix or revert the changeset before marking it as harmful.

**Comment by alexandre-mbm** [comment] 2016-01-23 02:56
A changeset fixed or reverted continues being the same. Could have field to indicate fix or reversion, pointing to the news.

**Comment by alantrick** [comment] 2017-04-10 18:53
I recently came across a mostly fine changeset (https://osmcha.mapbox.com/47570017/) that was marked harmful by someone. I suspect it was an accident, but there's no way to correct it apart from messaging the original verifier.

**Closed** 2017-08-04 21:22 UTC
