### ISSUE TITLE
Using osmcha to detect vandals

### ISSUE THREAD

**Issue by planemad** [willemarcel/osmcha-django#14] opened 2016-01-14 15:09 UTC
@willemarcel first off, love your work in making osmcha, its one of the most promising monitoring tools I have come across for mappers to keep a track of changes to their area. My colleage @batpad just setup **[a custom instance](http://osmcha-django-staging.tilestream.net)** that I have been poking around with to see if it can be used to catch map vandals :skull: , a technically challenging problem that nobody has successfully solved.

I'm interested in spending some more time exploring osmcha to review the flagged changesets and provide feedback to improve the detection rules, but it has been hard to keep up with the growing volume of data everyday. Is there any mechanism to quickly filter the data to a smaller subset that would make it easier to review?

**Comment by willemarcel** [comment] 2016-01-14 16:37
Hi, @planemad

A way of filtering the changesets is to pass a GeoJSON file in the django settings but you should have done it before importing. See https://github.com/willemarcel/osmcha-django/issues/9

However, you can filter it in the django shell and obtain a list of changesets in some part of the world (https://docs.djangoproject.com/en/1.9/ref/contrib/gis/geoquerysets/#std:fieldlookup-intersects)

**Comment by batpad** [comment] 2016-01-15 05:40
@willemarcel so, I think at this point the problem is a bit that there are a large amount of false positives - especially "Possible import" since many people create legitimate changesets with more than 200 features added.

Here are some possible ideas I had:

 - Allow greater filtering in the interface itself (by bbox, by number of changes, etc.), a little related to #7 
 - Allow the analysis parameters in `osmcha` to be configurable - so for eg. in my instance if I want Possible Import to be flagged for > 500 additions and not 200, I can configure this somewhere.
 - Develop a way to "white-list" users - i.e. if I see a user coming up very often in the suspicious list, but I know that user is an experienced mapper who knows what they are doing, I can white-list that user and not have their changesets show up as suspicious any more.

These are quite rough ideas right now and I am not sure of the implementation and think this would require a bit of discussion and trial and error to get right. @willemarcel do any of the above ideas seem interesting and doable (I'm happy to work on them, of course)? Have you had any thoughts about this? Would love to hear what you think. Thanks!

**Comment by willemarcel** [comment] 2016-01-15 18:29
* Your idea of filtering is great, @batpad! We should implement this.
* Yes, I thought about make osmcha parameters configurable, mainly because the suspect words analysis to allow include local terms.
* About the "white-list", I have thought about making a "black list". If someone thinks in using osmcha internally I see it as good idea. However in a comunitary instance, I think it's better to be transparent and put all the users at the same level. So we should implement this and each instance decides whether wants to use it or no.

**Comment by planemad** [comment] 2016-01-16 07:49
@willemarcel @batpad While evaluating the changesets I realized my main objective was to establish if the user is experienced and trusted, or not. This is a combination of various factors:
- Profile information: photo, bio details, links to social media profile, no of followers/friends, amount of transparency and detail in communication
- No of changesets/edits
- No of traces uploaded
- Detail in changeset comment and history of changesets 

By this time I usually know that the mapper knew what they were doing and was not hiding anything, in which case there is not much reason to suspect the edits were malicious. Any further changesets from the same user, I would ignore as wel considering good faithl, and this is probably where the concept of a whitelist is useful, but this should be a per reviewer setting and not a global list of whitelisted users.

Pretty much the same case for a blacklist, where I might want to examine edits of a suspect user more closely than others to establish if there is something odd going on. Usually just one changeset is not enough to confirm there may be a problem.

**Comment by willemarcel** [comment] 2016-01-18 00:47
Per reviewer setting to black and white listed users is such a great idea, @planemad!

Maybe in the future we could put yet more intelligence and the number of objects created/modified/deleted necessary to define a changeset as suspect vary based on the number of changesets marked as good or harmful of the user.

**Comment by batpad** [comment] 2016-01-18 10:42
To summarize points above and add some of my own thoughts about the users question:

 - When importing changesets, fetch additional metadata about the user. We would need to either find an existing API that allows us to query it, or build our own for this. Would be something like this: http://hdyc.neis-one.org/user/PlaneMad (we would need to ask permission if we want to use this, but am giving it as an example here). We then store those extended attributes in a `users` table or so in osmcha-django. We can then users the user attributes to filter changesets - for eg. if we don't want to see changesets by a user who has more than 10,000 edits to their name, etc.

 - Give instances the option to have something like USERS_WHITELIST defined in project `settings`. I am not very happy with this idea for the same reason you mention, @willemarcel - it will not be suitable for a community instance.

 - Track the number of changesets of each user that has been marked "verified good" and "verified bad". Display this number on the changesets list and allow people to filter by this. So, for eg. I can say "do not show me changesets for users that have more than 5 changesets already verified as good". Or, the reverse, "filter to show me all changesets of users that have had at least 1 changeset marked as bad".

 - Maintain a "per reviewer" white-list and black-list. So I can white-list a user and their changesets will never show up as suspicious for me, but will still show up for other users.

@willemarcel if any / all of these seem interesting to implement, let me know and I'll open separate tickets for each and we can see how best to implement. Thanks :)

**Closed** 2017-06-23 01:41 UTC
